# Generated by Django 4.0 on 2022-05-02 15:55

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time_slot', models.DateTimeField(default=datetime.datetime(2022, 5, 2, 23, 55, 43, 361633))),
                ('available_tables', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tables_booked', models.IntegerField(default=1)),
                ('booked_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='bookings.timeslot')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='booking', to='accounts.user')),
            ],
        ),
    ]
