# Generated by Django 4.0 on 2021-12-17 13:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='time_slot',
            new_name='booked_slot',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='booked_date',
        ),
        migrations.RemoveField(
            model_name='timeslot',
            name='date',
        ),
        migrations.RemoveField(
            model_name='timeslot',
            name='time_slot',
        ),
        migrations.AddField(
            model_name='timeslot',
            name='date_time_slot',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 17, 13, 0, 7, 469049)),
        ),
    ]
