# Generated by Django 4.0 on 2022-05-04 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeslot',
            name='available_tables',
        ),
        migrations.RemoveField(
            model_name='timeslot',
            name='date_time_slot',
        ),
        migrations.AddField(
            model_name='timeslot',
            name='date_slot',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='maximum_tables',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='time_slot',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
