# Generated by Django 4.0 on 2021-12-17 19:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_rename_time_slot_booking_booked_slot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslot',
            name='date_time_slot',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 17, 19, 23, 25, 582150)),
        ),
    ]
