# Generated by Django 4.0 on 2022-05-15 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_booking_date_slot_booking_time_slot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslot',
            name='maximum_tables',
            field=models.IntegerField(default=10),
        ),
    ]
