# Generated by Django 4.0 on 2021-12-17 21:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_alter_timeslot_date_time_slot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslot',
            name='date_time_slot',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 17, 21, 4, 54, 772694)),
        ),
    ]
