# Generated by Django 4.0 on 2021-12-15 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='ordered',
        ),
        migrations.AddField(
            model_name='cart',
            name='ordered_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
