# Generated by Django 4.0 on 2021-12-17 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_alter_cartitem_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='ordered_on',
        ),
    ]
