# Generated by Django 4.0 on 2021-12-15 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitem',
            old_name='availablilty',
            new_name='availability',
        ),
    ]
