# Generated by Django 4.0 on 2021-12-17 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_remove_menuitem_image_menuitem_imageurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='imageURL',
            field=models.CharField(max_length=200),
        ),
    ]
