# Generated by Django 4.0 on 2022-05-15 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(default='l0GozsiJFIC0x03', editable=False, max_length=15, primary_key=True, serialize=False, unique=True),
        ),
    ]
