# Generated by Django 4.0 on 2022-05-18 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(default='lCwao_2G4mLi-oI', editable=False, max_length=15, primary_key=True, serialize=False, unique=True),
        ),
    ]
