# Generated by Django 4.0 on 2021-12-17 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_user_salutation_deliveryaddress_unit_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryaddress',
            name='unit_no',
            field=models.CharField(max_length=50),
        ),
    ]
