# Generated by Django 4.0 on 2022-05-27 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(default='ADAKSt7iq-fxhiE', editable=False, max_length=15, primary_key=True, serialize=False, unique=True),
        ),
    ]
