# Generated by Django 4.0.4 on 2022-05-29 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(default='seYmcyWrn7l1qSJ', editable=False, max_length=15, primary_key=True, serialize=False, unique=True),
        ),
    ]
