# Generated by Django 4.0.4 on 2022-06-20 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(default='8gEIObQHA--bRjt', editable=False, max_length=15, primary_key=True, serialize=False, unique=True),
        ),
    ]
